In [1]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [10]:
a = np.random.randint(0,10,5)
a

array([9, 9, 9, 1, 2])

In [11]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [12]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [22]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix.reshape(1,9)
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a = np.arange(0, 10, 2)
a

array([0, 2, 4, 6, 8])

In [24]:
a = np.linspace(0, 1, 5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
x = np.array([10, 20, 30])
y = np.array([1, 2, 3])

toplam = np.add(x, y)
toplam


array([11, 22, 33])

In [28]:
fark = np.subtract(x, y)
fark 

array([ 9, 18, 27])

In [29]:
carpim = np.multiply(x, y)
carpim

array([10, 40, 90])

In [30]:
bolum = np.divide(x, y)
bolum

array([10., 10., 10.])