In [4]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5]) #tek boyutlu bir array oluşturduk
a

array([1, 2, 3, 4, 5])

In [ ]:
a = np.random.randint(0,10,5) #0-10 arasında 5 tane random sayı oluşturduk
a

array([9, 9, 9, 1, 2])

In [ ]:
a = np.zeros(5) #5 tane 0 olan array oluşturduk
a

array([0., 0., 0., 0., 0.])

In [ ]:
a = np.ones(5) #5 tane 1 olan array oluşturduk
a

array([1., 1., 1., 1., 1.])

In [ ]:
dizi = np.arange(1, 13)
matris = dizi.reshape(3, 4) #oluşan tek boyutlu diziyi 3x4 lük matrise şeklinde dönüştürdük.
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a = np.arange(0, 10, 2) #0'dan 10'a kadar 2'şer artan bir dizi oluşturduk
a

array([0, 2, 4, 6, 8])

In [ ]:
a = np.linspace(0, 1, 5) #0 ile 1 arasında 5 eşit parçaya bölünmüş bir dizi oluşturduk
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
x = np.array([10, 20, 30])
y = np.array([1, 2, 3])

toplam = np.add(x, y) #x ve y dizilerini topladık
toplam


array([11, 22, 33])

In [ ]:
fark = np.subtract(x, y) #x ve y dizilerini çıkardık
fark 

array([ 9, 18, 27])

In [ ]:
carpim = np.multiply(x, y) #x ve y dizilerini çarptık
carpim

array([10, 40, 90])

In [ ]:
bolum = np.divide(x, y) #x ve y dizilerini böldük
bolum

array([10., 10., 10.])